### ISSUE TITLE
Action to create a changelog

### ISSUE THREAD

**Issue by disrupted** [bakdata/ci-templates#8]
This is currently missing from the Poetry publish workflow, but would make for a useful addition.

_Originally posted by @disrupted in https://github.com/bakdata/ci-templates/issues/3#issuecomment-999616588_

**Comment by raminqaf** [comment]
We can use the [action-github-changelog-generator](https://github.com/heinrichreimer/action-github-changelog-generator) for generating the Changelog. A working example can be found at [Quick release workflow](https://github.com/bakdata/quick/blob/master/.github/workflows/release.yml#L50).

**Comment by yannick-roeder** [comment]
Closed with https://github.com/bakdata/ci-templates/pull/84

**Comment by torbsto** [comment]
## Problem

The proposed solution doesn't work out-of-the box because it expects an existing release. For example, let's say we've got a project with existing releases:
```
...
2.0.0
2.1.0
2.1.1
2.2.0
```
Without any input, the action would generate the changelog from `2.1.1` to `2.2.0`, i.e., the past two releases. 
This doesn't work for us because we want to generate the changelog from `2.2.0` to the next release, depending on the user supplied release type, e.g., `2.3.0` for minor. 
As the `toTag` must be a valid git ref, it seems like we can only achieve this by passing the default branch (main/master) as the argument to `toTag`. But this leads to the changelog containing the branch name instead of the new version. We would expect for the described scenario something like:

> ## [2.3.0](http://github.com/bakdata/example/tree/2.3.0) (2023-04-06)
>
> [Full Changelog](http://github.com/bakdata/example/compare/2.2.0...2.3.0)
>
> ### Features
>
> ...

but get with `main` as an argument (also note the links!):


> ## [main](http://github.com/bakdata/example/tree/main) (2023-04-06)
>
> [Full Changelog](http://github.com/bakdata/example/compare/2.2.0...main)
>
> ### Features
>
> ...


---


## Workflow

The action should support the following workflow (based on Quick and the Gradle-based releases) and implement the steps for 3.b:

```mermaid
flowchart TD

start[1: Manual trigger of release with $RELEASE_TYPE]
bump[2: Create $NEW_VERSION based on $RELEASE_TYPE]
versions[3.a: Update other versions like Helm chart or docs]
changelog[3.b.1: Create $RELEASE_CHANGELOG from latest release to $NEW_VERSION]
update[3.b.2: Prepend $RELEASE_CHANGELOG to CHANELOG.md]
commit[4: Create release commit]
tag[5: Tag release commit with $NEW_Version]
release[6: Create GitHub release with $RELEASE_CHANGELOG]

start --> bump
bump --> versions --> commit
bump --> changelog --> update --> commit
commit --> tag --> release
```

## Requirements

- [ ] Produces a release changelog with all closed PRs (**Note that this requires that you label the PRs accordingly**) since the last release
- [ ] The release changelog uses the user supplied git tag (that doesn't exist yet remotely) as the heading
- [ ] The release changelog uses the user supplied git tag for its links
- [ ] The release changelog is added to the CHANGELOG.md (file name can be overwritten by the user)
- [ ] The caller of the action can access the release changelog separately (for example, to add it to the GitHub release)
- [ ] Handles the first release of a project properly
